const sentenceBank = [
  "hello",
  "hey",
  "hi",
  "how are you",
  "how much is property allowance",
  "how much is trading allownace",
  "how to calculate tax",
  "how to tax profit from oversea company",
  "how to tax rental income from oversea property",
  "how to tax salary from oversea company",
  "what is being in employment",
  "what is capital gain tax",
  "what is dividend",
  "what is dividend income",
  "what is freelance work",
  "what is income tax",
  "what is income tax bands",
  "what is interest",
  "what is non resident",
  "what is non savings income",
  "what is pension",
  "what is pensions",
  "what is personal allowance",
  "what is personal savings allowance",
  "what is property allowance",
  "what is rental income",
  "what is resident",
  "what is savings income",
  "what is self assessment",
  "what is self assessment form",
  "what is self employed",
  "what is starting rate for savings",
  "what is tax free allowance",
  "what is tax year dates",
  "what is the tax year 2023",
  "what is trading allowance",
  "what is uk resident",
  "what is your name",
  "who are you",
  "who created you",
];

const botPreMadeReply = [
  "Hello new user, nice to meet you! I am a tax advisor chatbot for immigrants in the UK!",
  "Hi there! Thank you for using this tax advisor service!",
  "Hello, nice to meet you! Please press 'Start Advisor Chat' to begin the survey.",
  "I'm great! How about you?",
  "It is 1000 pounds",
  "It is 1000 pounds",
  "HMRC calculates how much tax you need to pay. It starts at your non-savings income, and then your savings income followed by your dividend income.",
  "As a UK resident, you need to pay tax on your income generated both in the UK and in foreign countries. Most foreign income is taxed in the same way as UK income. They will be calculated as part of your self-employed earning in the self-assessment form and maybe able to claim trading allowance.",
  "As a UK resident, you need to pay tax on your income generated both in the UK and in foreign countries. Most foreign income is taxed in the same way as UK income. They will be calculated as part of your self-employed earning in the self-assessment form and maybe able to claim property allowance.",
  "As a UK resident, you need to pay tax on your income generated both in the UK and in foreign countries. Most foreign income is taxed in the same way as UK income. They will be calculated as part of your self-employed earning in the self-assessment form and maybe able to claim trading allowance.",
  "You get wages when you are being in employment.",
  "Capital Gains Tax is a tax on the profit when you sell something that's increased in value. It's the gain you make that's taxed, not the amount of money you receive.",
  "It is a sum of money paid regularly by a company to its shareholders out of its profits.",
  "Dividend incomes are payments of income from companies in which you own stock.",
  "A freelance work is one where a person works for themselves, rather than for a company. Freelancers aren't employed by a company or committed to a single customer.",
  "Income Tax is a tax you pay on your earnings.",
  "Income Tax is made up of different bands. This means as your income increases, so does the amount of Income Tax you pay. Income tax on earned income is charged at three rates: the basic rate, the higher rate and the additional rate. Your personal allowance is up to £12,570.",
  "The money you earn on your savings is called interest.",
  "You're usually non-resident if either: you spent fewer than 16 days in the UK (or 46 days if you have not been a UK resident for the 3 previous tax years) you worked abroad full-time (averaging at least 35 hours a week), and spent fewer than 91 days in the UK, of which no more than 30 were spent working.",
  "Non-savings income includes wages, pensions, taxable state benefits, profits from self-employment and rental income.",
  "A regular income paid by a government to someone who no longer works.",
  "A regular income paid by a government to someone who no longer works.",
  "This is the amount of money you're allowed to earn each tax year before you start paying Income Tax.",
  "Your personal savings allowance is the total amount of interest you can earn each year across all of your bank accounts without paying tax.",
  "The property allowance is a tax exemption of up to £1,000 a year for individuals with income from land or property.",
  "Rental income is the rent you get from your tenants.",
  "You may be resident under the automatic UK tests if: you spent 183 or more days in the UK in the tax year. your only home was in the UK for 91 days or more in a row, and you visited or stayed in it for at least 30 days of the tax year.",
  "Savings income is interest earned on a cash balance whether paid to you by a bank, building society or any other source.",
  "Self assessment is a system HMRC uses to collect income tax.",
  "You tell HMRC about your taxable income and gains for a tax year by completing a Self Assessment tax return.",
  "A person is self-employed if they run their business for themselves and take responsibility for its success or failure.",
  "The starting rate for savings is a special 0% rate of income tax for savings income that falls within certain limits.",
  "There are a number of tax free allowance in the UK, such as personal allowance, property allowance, dividend allowance, marriage allowance, blind person's allowance and personal savings allowance.",
  "In the UK, the tax year start date is April 6th of each calendar year and the tax year end date is April 5th of the following year.",
  "The 2022 to 2023 tax year starts on 6 April 2022 and ends on 5 April 2023.",
  "The trading allowance exempts trading, casual and/or miscellaneous income of up to £1,000 per tax year from income tax and National Insurance contributions.",
  "You may be resident under the automatic UK tests if: you spent 183 or more days in the UK in the tax year. your only home was in the UK for 91 days or more in a row, and you visited or stayed in it for at least 30 days of the tax year.",
  "I am tax advisor chatbot!",
  "I am tax advisor chatbot!",
  "Nok Hang Tsang creates me!",
];

export { sentenceBank, botPreMadeReply };
